/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;

/**
 *
 * @author juand
 */
public class InterfazPokemon extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPokemon
     */
    public InterfazPokemon() {
        initComponents();
        txtEspecial.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtDefensa.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtAtaque.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtNivel.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtVelocidad.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtSliderMin.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtSliderMax.setBackground(new java.awt.Color(0, 0, 0, 1));
        setIconImage(new ImageIcon(getClass().getResource("/img/800px-Poké_Ball_icon.svg.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPokemon = new javax.swing.JLabel();
        txtPokemon = new javax.swing.JTextField();
        sliderMin = new javax.swing.JSlider();
        txtSliderMin = new javax.swing.JTextField();
        sliderMax = new javax.swing.JSlider();
        txtSliderMax = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        lblNivel = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        lblAtaque = new javax.swing.JLabel();
        txtAtaque = new javax.swing.JTextField();
        lblDefensa = new javax.swing.JLabel();
        txtDefensa = new javax.swing.JTextField();
        lblEspecial = new javax.swing.JLabel();
        txtEspecial = new javax.swing.JTextField();
        lblVelocidad = new javax.swing.JLabel();
        txtVelocidad = new javax.swing.JTextField();
        btnReiniciar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPokemon.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblPokemon.setForeground(new java.awt.Color(255, 255, 0));
        lblPokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPokemon.setText("Pokemon:");
        getContentPane().add(lblPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 110, 40));

        txtPokemon.setBackground(new java.awt.Color(204, 204, 204));
        txtPokemon.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        txtPokemon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemonActionPerformed(evt);
            }
        });
        getContentPane().add(txtPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 40));

        sliderMin.setBackground(new java.awt.Color(255, 255, 255));
        sliderMin.setForeground(new java.awt.Color(255, 255, 0));
        sliderMin.setMajorTickSpacing(1);
        sliderMin.setMaximum(20);
        sliderMin.setValue(0);
        sliderMin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMinStateChanged(evt);
            }
        });
        getContentPane().add(sliderMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, -1));

        txtSliderMin.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        txtSliderMin.setForeground(new java.awt.Color(255, 255, 255));
        txtSliderMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSliderMin.setText("1");
        txtSliderMin.setBorder(null);
        txtSliderMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSliderMinActionPerformed(evt);
            }
        });
        getContentPane().add(txtSliderMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 20, -1));

        sliderMax.setBackground(new java.awt.Color(255, 255, 255));
        sliderMax.setForeground(new java.awt.Color(255, 255, 0));
        sliderMax.setMajorTickSpacing(1);
        sliderMax.setMaximum(20);
        sliderMax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMaxStateChanged(evt);
            }
        });
        getContentPane().add(sliderMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 130, -1));

        txtSliderMax.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        txtSliderMax.setForeground(new java.awt.Color(255, 255, 255));
        txtSliderMax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSliderMax.setText("20");
        txtSliderMax.setBorder(null);
        txtSliderMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSliderMaxActionPerformed(evt);
            }
        });
        getContentPane().add(txtSliderMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 20, -1));

        btnGenerar.setBackground(new java.awt.Color(102, 102, 102));
        btnGenerar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 0));
        btnGenerar.setText("G E N E R A R");
        btnGenerar.setBorder(new javax.swing.border.MatteBorder(null));
        btnGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarMouseClicked(evt);
            }
        });
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 40));

        lblNivel.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblNivel.setForeground(new java.awt.Color(255, 255, 0));
        lblNivel.setText(" N i v e l :");
        getContentPane().add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 80, 30));

        txtNivel.setEditable(false);
        txtNivel.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        txtNivel.setForeground(new java.awt.Color(255, 255, 255));
        txtNivel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNivel.setBorder(null);
        getContentPane().add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 50, 30));

        lblAtaque.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblAtaque.setForeground(new java.awt.Color(255, 255, 0));
        lblAtaque.setText("A t a q u e :");
        getContentPane().add(lblAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 100, 30));

        txtAtaque.setEditable(false);
        txtAtaque.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        txtAtaque.setForeground(new java.awt.Color(255, 255, 255));
        txtAtaque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAtaque.setBorder(null);
        getContentPane().add(txtAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 50, 30));

        lblDefensa.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblDefensa.setForeground(new java.awt.Color(255, 255, 0));
        lblDefensa.setText(" D e f e n s a :");
        getContentPane().add(lblDefensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 140, 30));

        txtDefensa.setEditable(false);
        txtDefensa.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        txtDefensa.setForeground(new java.awt.Color(255, 255, 255));
        txtDefensa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDefensa.setBorder(null);
        getContentPane().add(txtDefensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 50, 30));

        lblEspecial.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblEspecial.setForeground(new java.awt.Color(255, 255, 0));
        lblEspecial.setText("E s p e c i a l :");
        getContentPane().add(lblEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 120, 30));

        txtEspecial.setEditable(false);
        txtEspecial.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        txtEspecial.setForeground(new java.awt.Color(255, 255, 255));
        txtEspecial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEspecial.setBorder(null);
        getContentPane().add(txtEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 50, 30));

        lblVelocidad.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblVelocidad.setForeground(new java.awt.Color(255, 255, 0));
        lblVelocidad.setText("V e l o c i d a d :");
        getContentPane().add(lblVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 140, 30));

        txtVelocidad.setEditable(false);
        txtVelocidad.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        txtVelocidad.setForeground(new java.awt.Color(255, 255, 255));
        txtVelocidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelocidad.setBorder(null);
        getContentPane().add(txtVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 50, 30));

        btnReiniciar.setBackground(new java.awt.Color(102, 102, 102));
        btnReiniciar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnReiniciar.setForeground(new java.awt.Color(255, 255, 0));
        btnReiniciar.setText("REINICIAR");
        btnReiniciar.setBorder(new javax.swing.border.MatteBorder(null));
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 130, 40));

        btnSalir.setBackground(new java.awt.Color(102, 102, 102));
        btnSalir.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 0));
        btnSalir.setText("X");
        btnSalir.setBorder(new javax.swing.border.MatteBorder(null));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 30, 20));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/photo-1595757816291-ab4c1cba0fc2.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        int level = (int) Math.floor(Math.random() * (sliderMax.getValue() - sliderMin.getValue() + 1) + sliderMin.getValue());
        txtNivel.setText(String.valueOf(level));
        
        int points = level + 5;
        txtVelocidad.setText(String.valueOf(points));
        int aleatorio = (int) Math.floor(Math.random() * (points / 2) + 1);
        int aleatorio2 = (int) Math.floor(Math.random() * (points / 2) + 1);
        ArrayList<Integer> numbers = new ArrayList<Integer>();
        numbers.add(aleatorio);
        numbers.add(aleatorio2);
        numbers.add(points - (numbers.get(0) + numbers.get(1)));
        Collections.shuffle(numbers);
        txtAtaque.setText("" + numbers.get(0));
        txtDefensa.setText("" + numbers.get(1));
        txtEspecial.setText("" + numbers.get(2));
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseClicked

    }//GEN-LAST:event_btnGenerarMouseClicked

    private void sliderMaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMaxStateChanged
        // TODO add your handling code here:
        txtSliderMax.setText(String.valueOf(sliderMax.getValue()));
        if (sliderMax.getValue() <= sliderMin.getValue() + 1) {
            sliderMin.setValue(sliderMin.getValue() - 2);
        }
    }//GEN-LAST:event_sliderMaxStateChanged

    private void txtSliderMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSliderMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSliderMaxActionPerformed

    private void sliderMinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMinStateChanged
        txtSliderMin.setText(String.valueOf(sliderMin.getValue()));
        if (sliderMin.getValue() >= sliderMax.getValue() - 1) {
            sliderMax.setValue(sliderMax.getValue() + 2);
        }
    }//GEN-LAST:event_sliderMinStateChanged

    private void txtSliderMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSliderMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSliderMinActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        txtPokemon.setText("");
        txtNivel.setText("");
        txtAtaque.setText("");
        txtDefensa.setText("");
        txtEspecial.setText("");
        txtVelocidad.setText("");
        txtSliderMax.setText("20");
        txtSliderMin.setText("1");
        sliderMax.setValue(20);
        sliderMin.setValue(1);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void txtPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblDefensa;
    private javax.swing.JLabel lblEspecial;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblPokemon;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JSlider sliderMax;
    private javax.swing.JSlider sliderMin;
    private javax.swing.JTextField txtAtaque;
    private javax.swing.JTextField txtDefensa;
    private javax.swing.JTextField txtEspecial;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtPokemon;
    private javax.swing.JTextField txtSliderMax;
    private javax.swing.JTextField txtSliderMin;
    private javax.swing.JTextField txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
